/*
 * AppConstants
 */
const SHOW_INFO_MESSAGE = 'App/SHOW_INFO_MESSAGE';
const HIDE_INFO_MESSAGE = 'App/HIDE_INFO_MESSAGE';
const SHOW_LOADING = 'App/SHOW_LOADING';
const HIDE_LOADING = 'App/HIDE_LOADING';
const UPDATE_LOADED_COMPLETE = 'App/UPDATE_LOADED_COMPLETE';
const CHANGE_CURRENT_FOLDER = 'App/CHANGE_CURRENT_FOLDER';
const IS_SAVE_INDICATOR_VISIBLE = 'App/IS_SAVE_INDICATOR_VISIBLE';
const HANDLE_PROGRESS_BAR = 'App/HANDLE_PROGRESS_BAR';
const SHOW_MODAL = 'App/SHOW_MODAL';
const HIDE_MODAL = 'App/HIDE_MODAL';
const SHOW_ADD_FOLDER_MODAL = 'App/SHOW_ADD_FOLDER_MODAL';
const HIDE_ADD_FOLDER_MODAL = 'App/HIDE_ADD_FOLDER_MODAL';
const TOOGLE_THEME = 'App/TOOGLE_THEME';
const TOOGLE_LANG = 'App/TOOGLE_LANG';
const CHANGE_DEMON_COUNTER = 'App/CHANGE_DEMON_COUNTER';
const UPDATE_SCREEN_INFO = 'App/UPDATE_SCREEN_INFO';
const UPDATE_IS_SEARCH_VISIBLE = 'App/UPDATE_IS_SEARCH_VISIBLE';
const UPDATE_CONTENTBOX_STATUS = 'App/UPDATE_CONTENTBOX_STATUS';
const UPDATE_CONTENTBOX_MESSAGE = 'App/UPDATE_CONTENTBOX_MESSAGE';
const UPDATE_GETEMAIL_STATUS = 'App/UPDATE_GETEMAIL_STATUS';
const UPDATE_EMAIL_LIST_LOADING_STATUS = 'App/UPDATE_EMAIL_LIST_LOADING_STATUS';

export {
  SHOW_INFO_MESSAGE,
  HIDE_INFO_MESSAGE,
  SHOW_LOADING,
  HIDE_LOADING,
  UPDATE_LOADED_COMPLETE,
  CHANGE_CURRENT_FOLDER,
  IS_SAVE_INDICATOR_VISIBLE,
  HANDLE_PROGRESS_BAR,
  SHOW_MODAL,
  HIDE_MODAL,
  SHOW_ADD_FOLDER_MODAL,
  HIDE_ADD_FOLDER_MODAL,
  TOOGLE_THEME,
  TOOGLE_LANG,
  CHANGE_DEMON_COUNTER,
  UPDATE_SCREEN_INFO,
  UPDATE_IS_SEARCH_VISIBLE,
  UPDATE_CONTENTBOX_STATUS,
  UPDATE_CONTENTBOX_MESSAGE,
  UPDATE_GETEMAIL_STATUS,
  UPDATE_EMAIL_LIST_LOADING_STATUS,
};
